trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - lms-negotiation/**
      - pipelines/**

variables:
  - group: LMS-Core-Versions

name: $(Prod-Version)

stages:
  - template: Templates/build-template.yml
    parameters:
      variableGroupName: "LMS-Core-Prod"
      vmImageName: "windows-latest"

  - template: Templates/release-template.yml
    parameters:
      variableGroupName: "LMS-Core-Prod"
      azureSubscription: "LMS Service Connection - PROD"
      environment: "Production"
      vmImageName: "windows-latest"
